version: "3"

services:
  db:
    container_name: fastapi_web
    image: postgres:13
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn server:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/usr/src/app
    expose:
      - 8000
    depends_on:
      - db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=psql@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 127.0.0.1:1337:1337
    depends_on: 
      - web
volumes:
  postgres_data:
