version: "3"

services:
  db:
    image: postgres:13
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: bash -c "alembic upgrade head && python3 server.py"
    volumes:
      - .:/usr/src/app
    expose:
      - ${PORT}
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=psql@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5500
    ports:
      - 127.0.0.1:5501:5500
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 127.0.0.1:1337:1337
    depends_on: 
      - web
volumes:
  postgres_data:
