version: "3"

services:
  db:
    image: postgres:13
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: bash -c "uvicorn server:app --port 8000"
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - db
volumes:
  postgres_data:
