version: "3"

services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn server:app --host ${HOST} --port ${PORT} --reload"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:${PORT}"
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  postgres_data: