"""empty message

Revision ID: 0a3305fe638a
Revises: cf78843e233b
Create Date: 2021-03-26 00:55:13.135029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a3305fe638a'
down_revision = 'cf78843e233b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_short_urls_id', table_name='short_urls')
    op.drop_table('short_urls')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('short_urls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('base_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('short', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('counter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='short_urls_pkey')
    )
    op.create_index('ix_short_urls_id', 'short_urls', ['id'], unique=False)
    # ### end Alembic commands ###
