"""empty message

Revision ID: 1f87cb9dac90
Revises: 0c4ad4a4e12a
Create Date: 2021-03-22 02:15:28.904585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f87cb9dac90'
down_revision = '0c4ad4a4e12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_short_url_id', table_name='short_url')
    op.drop_table('short_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('base_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('short', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('counter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='short_url_pkey')
    )
    op.create_index('ix_short_url_id', 'short_url', ['id'], unique=False)
    # ### end Alembic commands ###
