"""empty message

Revision ID: bdbe397b5b6d
Revises: 6a5c70953ece
Create Date: 2021-03-22 00:44:52.377994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdbe397b5b6d'
down_revision = '6a5c70953ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_short_url_id', table_name='short_url')
    op.drop_table('short_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('base_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('short', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('counter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='short_url_pkey')
    )
    op.create_index('ix_short_url_id', 'short_url', ['id'], unique=False)
    # ### end Alembic commands ###
